hydra:
  job:
    chdir: false
    name: g1_thermo_diffusion
  run:
    dir: ./output/${hydra:job.name}
  searchpath:
    - pkg://conf/base

defaults:
  - dataset: hrrr_mini
  - model: diffusion
  - model_size: mini
  - training: ${model}

dataset:
  data_path: ./data/v4/randomly/train.nc
  stats_path: ./data/v4/randomly/stats.json
  output_variables: ['2t', '10u', '10v', 'sp', 'q']

training:
  hp:
    training_duration: 25000000
  io:
    checkpoint_dir: checkpoints_g1_diffusion
    print_progress_freq: 10000
    regression_checkpoint_path: ???

wandb:
  mode: offline
  results_dir: "./wandb"
  watch_model: false
